### PR TITLE
feat(index.d.ts): add type info to Symbol.observable

### PR DESCRIPTION
**Pull request by appsforartists**
Closes https://github.com/blesh/symbol-observable/issues/27

### CODE REVIEW

**Comment by benlesh** [comment]
@appsforartists it looks like it's failing the TSC build test.

```
index.d.ts(6,5): error TS1131: Property or signature expected.
index.d.ts(6,14): error TS1005: ';' expected.
index.d.ts(8,1): error TS1128: Declaration or statement expected.
index.d.ts(11,3): error TS1131: Property or signature expected.
index.d.ts(11,31): error TS1005: ';' expected.
index.d.ts(12,1): error TS1128: Declaration or statement expected.
```

Everything looks okay though... Hmm... maybe something about the version of TypeScript we're using? cc/ @mhegazy @david-driscoll

**Comment by mhegazy** [comment]
[`readonly` is a TS 2.0 feature](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#read-only-properties-and-index-signatures), the build is [using TS 1.8](https://github.com/blesh/symbol-observable/blob/7fd288102ed5cc48c5081b2a8299eae5a5dd3544/package.json#L45)

**Comment by benlesh** [comment]
I figured it was something like that.

**Comment by benlesh** [comment]
@mhegazy would it be most compatible if I removed the `readonly` then?

**Comment by benlesh** [comment]
Closed in favor of #29, which is a continuation of this PR (it includes @appsforartists' commit).

**Comment by benlesh** [comment]
BTW: Thanks @mhegazy I think we have it straightened out now

**Pull request closed without merging**
