### PR TITLE
Addendum to #11... adding TS test

### PR DESCRIPTION
**Pull request by benlesh**
Attn @robwormald... this is an extension on your PR #11, including your commits. Just adding a test to see if everything is kosher.

### CODE REVIEW

**Comment by robwormald** [comment]
The problem I'm seeing has to do with how TS vs JS treat the import. I think it's the old .default issue 😐

**Comment by benlesh** [comment]
yup

**Comment by benlesh** [comment]
Okay, so digging into this, it's not possible do support both types of exports. I can't assign a `default` property on a Symbol. and I can't use `Object.defineProperty` on a non-object (symbol).

So we're stuck with exporting a named variable, or just exporting `default` so CJS users get the `require('symbol-observable').default` thing or they have `require('symbol-observable').symbolObservable` or something. :\

Yay modules.

**Comment by benlesh** [comment]
cc/ @gaearon .... what do you think?

**Comment by benlesh** [comment]
So I need to fix this for RxJS and Angular, for sure... @gaearon, you're the only other "big customer", do you have a preference on how to solve this problem? (also would you like commit rights on this repo?)

**Comment by benlesh** [comment]
The proposed solutions are:
1. CJS uses `require('symbol-observable').default` 
2. CJS uses `require('symbol-observable').symbolObservable` (or something like that)

**Comment by gaearon** [comment]
I think `.default` is reasonable.

**Comment by robwormald** [comment]
Agreed, lets optimize for the future

**Comment by benlesh** [comment]
Closing in favor of #15

**Pull request closed without merging**
